---
title: "Technology, Quality of Life, and Relationships"
output: html_document
---

```{r loading libraries, echo=FALSE}
#Loading libraries
library(ggplot2)
library(gridExtra)

#Loading Data
df <- read.csv("May_2013_Online_Dating_CSV.csv")
```


```{r gender, echo=FALSE}
# Gender plot
df[, "sex"] <- as.factor(df[, "sex"])
#summary(df[, "sex"])
#str(df[, "sex"])

gender <- ggplot(data = df, aes(x = sex, fill = sex)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1" = "Male", "2" = "Female")) +
  labs(x = "Gender", y = "Count", title = "Gender")
```

```{r sexual orientation, echo=FALSE}
# Sexual orientation plot
df[, "lgbt"] <- as.factor(df[, "lgbt"])
#summary(df$lgbt)
#str(df$lgbt)

sexual_orientation <- ggplot(data = df, aes(x = lgbt)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1" = "Heterosexual", "2" = "Gay/lesbian", "3" = "Bisexual", "4" = "Other", "8" = "Don't know", "9" = "Refused")) + coord_flip() +
  labs(x = "", y = "Count", title = "Sexual Orientation")
  
```

```{r age, echo=FALSE}
#Age plot
#summary(df$age)
#str(df$age)

age <- ggplot(data = df, aes(x = age)) + 
  geom_histogram(binwidth = 5, color="black", fill="orange") + 
  scale_x_continuous(limits = c(15,100), breaks = seq(0, 100, 10)) +
  labs(x = "Age", y = "Frequency", title = "Age")

```

```{r race, echo=FALSE}
# Race plot
df[, "race"] <- as.factor(df[, "race"])
#summary(df$race)
#str(df$race)

r_race <- ggplot(data = df, aes(x=reorder(race, -table(race)[race]))) + 
  geom_bar() + 
  scale_x_discrete(labels=c("1" = 'White',"2" = 'Black',"3" = 'Asian',"4" = 'Mixed',"5" = 'Native American',"6" = 'Other',"8" = "Don't Know","9" = 'Refused')) +
  labs(x = "", y = "Count", title = "Race") +
  coord_flip()
```


# Who were the respondents (part 1)
```{r describtive_stats_1, echo=FALSE}
grid.arrange(gender, r_race, age, hispanic)
```


```{r employment, echo=FALSE}
# Employment plot
df[, "emplnw"] <- as.factor(df[, "emplnw"])
#summary(df$emplnw)
#str(df$emplnw)

employment <- ggplot(data = df, aes(x=reorder(emplnw, -table(emplnw)[emplnw]))) + 
  geom_bar() + 
  scale_x_discrete(labels=c("1" = 'Full-time',"2" = 'Part-time',"3" = 'Retired',"4" = 'Not employed',"5" = 'Self-employed',"6" = 'Disabled',"7" = "Student", "8" = 'Other', "9" = "Refused")) +
  labs(x = "", y = "Count", title = "Employment Level") + coord_flip()
```


```{r income, echo=FALSE}
# Income plot
df[, "inc"] <- as.factor(df[, "inc"])
#summary(df$inc)
#str(df$inc)

income <- ggplot(data = df, aes(x = inc)) + 
  geom_bar() + coord_flip() +
  scale_x_discrete(labels = c("1" = "under 10k", "2" = "10-20k", "3" = "20-30k", "4" = "30-40k", "5" = "40-50k", "6" = "50-75k", "7" = "75-100k", "8" = "100-150k", "9" = "over 150k", "98" = "Don't Know", "99" = "Refused")) +
  labs(x = "", y = "Count", title = "Income in thousands USD")
  
```

```{r education, echo=FALSE}
# Education plot
df[, "educ2"] <- as.factor(df[, "educ2"])
#summary(df$educ2)
#str(df$educ2)

education <- ggplot(data = df, aes(x = educ2)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1" = "Grade 1-8", "2" = "Incomplete high school", "3" = "Complete high school", "4" = "Some college", "5" = "Associate degree", "6" = "Bachelor's", "7" = "Some postgrad", "8" = "Master's/phd/professional", "98" = "Don't know", "99" = "Refused")) +
  labs(x = "", y = "Count", title = "Education") + coord_flip()
```

<<<<<<< HEAD
```{r household size, echo=FALSE}
# Household size plot
df[, "hh1"] <- as.factor(df[, "hh1"])
#summary(df$hh1)
#str(df$hh1)

household_size <- ggplot(data = df, aes(x = hh1)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1" = "1", "2" = "2", "3" = "3", "4" = "4", "5" = "5", "6" = "6+", "8" = "Don't know", "9" = "Refused")) +
  labs(x = "", y = "Count", title = "Household Size")
```

# Who were the respondents (part 2)
```{r describtive_stats_2, echo=FALSE}
grid.arrange(employment, education, income, household_size)
```


```{r marrital status, echo=FALSE}
# Marital status
df[, "mar"] <- as.factor(df[, "mar"])
#summary(df$mar)
#str(df$mar)

marital_status <- ggplot(data = df, aes(x = mar)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1"="Married", "2"="Living with Partner", "3"="Divorced", "4"= "Separated", "5" = "Widowed", "6" = "Never been married", "8" = "Don't know", "9" ="Refused")) +
  labs(x = "", y = "Count", title = "Marital status") + coord_flip()
```


```{r children, echo=FALSE}
# Children
df[, "par"] <- as.factor(df[, "par"])
#summary(df$par)
#str(df$par)

children <- ggplot(data = df, aes(x = par)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1"="Yes", "2"="No", "8" = "Don't know", "9" ="Refused")) +
  labs(x = "", y = "Count", title = "Children <18 living in household")
```

```{r Hispanic, echo=FALSE}
# Hispanic
df[, "hisp"] <- as.factor(df[, "hisp"])
#summary(df$hisp)
#str(df$hisp)

hispanic <- ggplot(data = df, aes(x = hisp)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1"="Yes", "2"="No", "8" = "Don't know", "9" ="Refused")) +
  labs(x = "", y = "Count", title = "Are you of Hispanic or Latino background?")
```


```{r life quality, echo=FALSE}
# Life quality
df[, "q1"] <- as.factor(df[, "q1"])
#summary(df$q1)
#str(df$q1)

life_quality <- ggplot(data = df, aes(x = q1)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1"="Excellent", "2"="Vert good", "3" = "Good", "4" = "Fair", "5" = "Poor", "8" = "Don't know", "9" ="Refused")) +
  labs(x = "", y = "Count", title = "Quality of life") + coord_flip()
```

#Who were the respondents (part 3)

```{r describtive_stats_3, echo=FALSE}
grid.arrange(marital_status, sexual_orientation, children, life_quality)
```

#Happiness vs presence of children in the household

```{r life quality vs children, echo=FALSE}
# Life quality vs children

life_quality_vs_children <- ggplot(data = df, aes(x = q1)) + 
  geom_bar() + 
  scale_x_discrete(labels = c("1"="Excellent", "2"="Vert good", "3" = "Good", "4" = "Fair", "5" = "Poor", "8" = "Don't know", "9" ="Refused")) +
  labs(x = "", y = "Count", title = "Quality of life vs Children in the household") + facet_wrap(~par)
```


```{r} 
##### SAUL & UDIT's Part ----- Technology and Relationship

# 1 Ex. Do people that met online [rel1, 1] perceive their quality of life higher [q1] or lower?

onlineRel <- mean((df[df[,"rel1"] == 1, "q1"]), na.rm = TRUE)
offlineRel<- mean((df[df[,"rel1"] == 2, "q1"]), na.rm = TRUE)

hist((df[df[,"rel1"] == 1, "q1"]), na.rm = TRUE)

hist((df[df[,"rel1"] == 2, "q1"]), na.rm = TRUE)



# 2 Does technology assist in meeting a partner? 




# 3 Is there a difference between people’s happiness with their partner for those who met their person online vs offline?



# 4 For people who say that they are looking for a partner, look at the proportion of who are using online dating


sum(((df[,"mar4"] == 1) *1), na.rm = TRUE) # total number of people looking for a relationship 



sum((df[df[,"mar4"] == 1, "date6"] == 1)*1, na.rm = TRUE) #number of people that are looking for a relationship & using online dating 
sum((df[df[,"mar4"] == 1, "date6"] == 2)*1, na.rm = TRUE) #number of people that are looking for a relationship &  are NOT using online dating 



# 5 For people that say it’s difficult / easy to meet people in their city/state, see how many people using online dating?

sum((df$meet == 1), na.rm = TRUE) #easy to meet 
sum((df$meet == 2), na.rm = TRUE) # difficult 



sum((df[df[,"date6"] == 1 , "meet"] == 1) , na.rm =  TRUE) # number of people with an online dating page, that find it easy to meet people 

sum((df[df[,"date6"] == 1 , "meet"] == 2) , na.rm =  TRUE) # number of people with an online dating page, that find it difficult  to meet people 


sum((df[df[,"date6"] == 1 , "meet"]) , na.rm =  TRUE) # 59 people with dating pages answered the question about th edifficulty to meet people. 

summary(df[,"date6"] == 1) 

summary(df[,"meet"] == 1 )


# 6 Does meeting a partner online fostering a bonding relationship with partner? For example, from the question about someone believes that internet / cellphone have a NEGATIVE / ZERO impact with relationship [REL6/ REL7] → see % of them that use cellphone to send / receive nude pictures [Q13] and not having any fight within 30 days [REL8] ☺ ☺



# 7 Ex. How is the use of Social Media Networks and Twitter affect relationships?
#Can we see the relationship between marital status [MAR] / gender [SEX] / confident [DATE7] / social activity [LOC3] with using online dating  [DATE1A / DATE2A]? For example to see married men / women use online dating as well ☺ ? The initial hypothesis is that: only single / divorced men / women that use online dating



# 8 Relationship between privacy [REL4 and REL5] and having a fight in a relationship [REL8]? Does person who shares password/account together tend to have more fights than those who are not?




# 8 Would you say that technolgy is having a major impact on your relationship

sum(((df[,"rel6"] == 1)* 1), na.rm = TRUE) #major
sum(((df[,"rel6"] == 2)* 1), na.rm = TRUE) #minor
sum(((df[,"rel6"] == 3)* 1), na.rm = TRUE) #no effect



```


```{r} 
##### Shieron's Part ----- Technology and Income

df <- read.csv("May_2013_Online_Dating_CSV.csv")

####################################################################################################
# 1 Does the person's income determine smartphone being used?

# Group discrete variables for smartphone (smart2) and income (inc)
df[,"smart2"] <- as.numeric(df[,"smart2"])
df [!is.na(df$smart2) & df$smart2 > 5,]$smart2 <- 9
df [!is.na(df$inc) & df$inc < 4,]$inc <- 1
df [!is.na(df$inc) & df$inc > 3 & df$inc < 7,]$inc <- 2
df [!is.na(df$inc) & df$inc > 6 & df$inc < 9,]$inc <- 3
df [!is.na(df$inc) & df$inc > 10,]$inc <- 99
df[,"smart2"] <- as.character(df[,"smart2"])
df[,"inc"] <- as.character(df[,"inc"])

ggplot(data = subset(df, !is.na(df$smart2)),aes (x = inc, fill = smart2, order = -as.numeric(smart2))) + geom_bar () + scale_x_discrete(labels = c("1"="<30K", "2"="30K - 75K", "3"="75K - 150K", "9"=">150K", "99" = "N/A")) + scale_fill_discrete(name = "Smartphone", breaks = c ("1", "2", "3", "4", "9"), labels = c("iPhone", "Blackberry", "Android", "Windows", "Others")) + labs(x = "Income (in US$)", y = "Count", title = "Smartphone and Income") 

####################################################################################################
# 2 Does a person who generates higher income and has smartphone tend to access email and browse internet? In other words, do accessing email and browsing internet depend with smartphone and income?

df[(!is.na(df$q11a) & df$q11a == 1) |(!is.na(df$q11c) & df$q11c == 1) , "email_internet"] <- 1
df[(!is.na(df$q11a) & df$q11a == 2) |(!is.na(df$q11c) & df$q11c == 2) , "email_internet"] <- 0

model_out1 <- glm (email_internet ~ smart2 + inc, data = df, family = "binomial")
coef (summary(model_out1))

ggplot(data = df[(df[,"inc"] != "99"),], aes(x = inc , y = smart2)) + geom_tile(aes(fill=email_internet)) + scale_x_discrete(labels = c("1"="<30K", "2"="30K - 75K", "3"="75K - 150K", "9"=">150K", "99" = "N/A")) + scale_y_discrete(breaks = c ("1", "2", "3", "4", "9"), labels = c("iPhone", "Blackberry", "Android", "Windows", "Others")) + scale_fill_continuous(limits=c(0, 1), breaks=rev(seq(0,1,by=1)), name = "Access Email / Internet", labels = c ("Yes, I use my phone", "No, I don't")) + labs(x = "Income (in US$)", y = "Smartphone", title = "Income, Smartphone, and Email / Internet Access") 

####################################################################################################
# 3 Does a person who generates high income use internet at their home? It can show how they are dependent/not with the internet
# If they use internet, what connection they use (do people still use dial up)

model_out2 <- glm (home3nw ~ inc, data = df, family = "binomial")
coef (summary(model_out2))
       
ggplot(data = transform(df, home3nw = c("Yes, I use internet", "No, I don't", "I don't know", "N/A")[as.numeric(home3nw)]), aes(x = inc, fill = inc)) + geom_bar() + facet_grid (home3nw ~ .) + scale_x_discrete(labels = c("1"="<30K", "2"="30K - 75K", "3"="75K - 150K", "9"=">150K", "99" = "N/A")) + labs(x = "Income (in US$)", y = "Count", title = "Income and Using Internet at Home") + theme(legend.position="none")

ggplot(data = transform(df[df[,"home3nw"] == 1 & df[,"modem4b"] < 8,], modem4b = c("Dial-up", "DSL-enabled phone line", "Cable modem", "Wireless", "Fiber optic")[as.numeric(modem4b)]), aes(x = inc, fill = inc)) + geom_bar() + facet_grid (modem4b ~ .) + scale_x_discrete(labels = c("1"="<30K", "2"="30K - 75K", "3"="75K - 150K", "9"=">150K", "99" = "N/A")) + labs(x = "Income (in US$)", y = "Count", title = "Income and Using Internet at Home") + theme(legend.position="none", strip.text.x = element_text(size = 4, colour = "black", angle = 90))

```

>>>>>>> 13632aef6cb16813c8cc22d79e0d399e339973b4
